package com.uxstudio.contacts.infrastructure.persistence

import com.uxstudio.contacts.domain.models.Contact
import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.index.Indexed
import org.springframework.data.mongodb.core.mapping.Document

/**
 * Represents the persistence entity for contacts in MongoDB.
 *
 * This class serves as the bridge between the database layer and the core domain model.
 * It implements the [PersistenceEntity] interface to ensure consistent data mapping.
 *
 * @property id Unique identifier generated by MongoDB.
 * @property imageId Reference to the contact's profile image stored in the file storage service.
 * @property name The full name of the contact.
 * @property phoneNumber International format telephone number (e.g., +36...).
 * @property email Unique email address used as a lookup index and primary contact method.
 */
@Document(collection = "contacts")
data class ContactEntity(
    @Id val id: String? = null,
    val imageId: String? = null,
    val name: String,
    val phoneNumber: String,
    @Indexed(unique = true) val email: String
) : PersistenceEntity<Contact> {

    /**
     * Maps the persistence entity to the pure [Contact] domain model.
     * @return A validated [Contact] domain object.
     */
    override fun toDomain() = Contact(
        id = id,
        imageId = imageId,
        name = name,
        phoneNumber = phoneNumber,
        email = email
    )

    companion object {
        /**
         * Static factory method to create a [ContactEntity] from a [Contact] domain model.
         * * @param contact The pure domain object.
         * @return An infrastructure-ready [ContactEntity].
         */
        fun fromDomain(contact: Contact) = ContactEntity(
            id = contact.id,
            imageId = contact.imageId,
            name = contact.name,
            phoneNumber = contact.phoneNumber,
            email = contact.email
        )
    }
}